version: '3'
services:
  btcpd:
    tty: true
    build: .
    restart: always
    image: btcp:0.0.1
    volumes:
     - ./data:/coin/data
     - ./coin.conf:/root/.btcprivate/btcprivate.conf
     - ./coin.conf:/coin/btcprivate.conf
    ports:
       - 7932:7932
